#ifndef CONSTANTS_H
#define CONSTANTS_H

//PINS
#define QRD_TAPE_RIGHT 0
#define QRD_TAPE_LEFT 1
#define QRD_AGENT_TAPE_LEFT 2
#define QRD_AGENT_TAPE_RIGHT 3
#define TEN_KHZ_IR_PIN 4
#define ONE_KHZ_IR_PIN 5

#define MOTOR_LEFT 0
#define MOTOR_RIGHT 1

#define NUM_VARIABLES 6
#define MENU_BLINK_TIME 500
#define MENU_MAX_K 100
#define GAIN_KP 50
#define GAIN_KD 4
#define GAIN_KI 0
#define GAIN_K 1
#define MAX_VOLTAGE 1023.0

#define QRD_THRESHOLD 100

#define REGULAR_SPEED 120
#define HILL_SPEED 100
#define MAX_SPEED 255
#define MIN_SPEED -255

#define STARTING_BASE_ANGLE 90
#define STARTING_ARM_ANGLE 100
#define OPEN_HAND_ANGLE 100
#define CLOSE_HAND_ANGLE 10

#define ERROR_RIGHT_HALF 1
#define ERROR_RIGHT_FULL 3
#define ERROR_LEFT_HALF -1
#define ERROR_LEFT_FULL -3

#define NUM_AGENTS 6

#define ARM_DELAY 0.5
#define BASE_DELAY 0.7
#define MIN_ARM_DELAY 3
#define MIN_BASE_DELAY 10
#define CLAW_DELAY 250

#define HIGH_LIMIT 5
#define LOW_LIMIT -5

#endif
